# Generated by Django 4.2.5 on 2023-11-16 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subEntrado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subEntrado.department')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='person_of_intrest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subEntrado.staff'),
        ),
    ]
