# Generated by Django 4.2.5 on 2023-11-16 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subEntrado', '0002_staff_alter_appointment_person_of_intrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staffID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subEntrado.staff'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='person_of_intrest',
            field=models.CharField(max_length=100),
        ),
    ]
