# Generated by Django 4.2.5 on 2023-11-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subEntrado', '0003_appointment_staffid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='staffID',
            new_name='staff',
        ),
    ]
