# Generated by Django 4.2.5 on 2023-11-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subEntrado', '0005_alter_appointment_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='staff',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='person_of_intrest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subEntrado.staff'),
        ),
    ]
