# Generated by Django 4.2.5 on 2023-11-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subEntrado', '0009_alter_staff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
