# Generated by Django 4.2.5 on 2023-11-18 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subEntrado', '0010_department_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='active',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subEntrado.department'),
        ),
    ]
