# Generated by Django 4.2.5 on 2023-11-19 19:52

from django.db import migrations, models
import subEntrado.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subEntrado', '0011_remove_department_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True, validators=[subEntrado.validators.validate_within_time_range]),
        ),
    ]
